#!/usr/bin/env python3
"""Summarize development-only, paired JRDB annotation projection diagnostics.

Both inputs were generated by audit_jrdb_dev_native_2d_3d_reprojection.py.
This script reads annotation diagnostics offline. It cannot score detectors,
sensor-derived range, synchronization or proximity alerts.
"""

import argparse
import csv
import hashlib
import json
import math
import statistics
from collections import Counter, defaultdict
from pathlib import Path


SEQUENCE = "cubberly-auditorium-2019-04-22_0"
STATUSES = {"inside_2d_box", "outside_2d_box", "outside_camera_image"}
REQUIRED = {"frame", "camera", "label_id", "3d_xy_radius_m", "2d_box_xywh",
            "2d_no_eval", "2d_occlusion", "2d_truncated", "upper_center_status",
            "ego_center_status", "upper_outside_box_px", "ego_outside_box_px"}
REVIEW_FIELDS = ("review_priority", "image_edge_box", "paired_outcome", "frame",
                 "camera", "label_id", "3d_xy_radius_m", "2d_box_xywh",
                 "2d_no_eval", "2d_occlusion", "2d_truncated", "upper_center_uv",
                 "upper_center_status", "upper_outside_box_px", "ego_center_uv",
                 "ego_center_status", "ego_outside_box_px")


def parse_bool(value, name):
    if isinstance(value, bool):
        return value
    if value is None or str(value).strip().lower() in {"", "none", "null"}:
        return None
    if str(value).lower() == "true":
        return True
    if str(value).lower() == "false":
        return False
    raise ValueError(f"Expected a Boolean {name}; got {value!r}")


def describe(rows):
    n = len(rows)
    upper = sum(r["upper_center_status"] == "inside_2d_box" for r in rows)
    ego = sum(r["ego_center_status"] == "inside_2d_box" for r in rows)
    outcomes = Counter(r["paired_outcome"] for r in rows)
    return {"pairs": n, "upper_inside": upper, "ego_inside": ego,
            "upper_inside_fraction": round(upper / n, 5) if n else None,
            "ego_inside_fraction": round(ego / n, 5) if n else None,
            "ego_minus_upper_fraction": round((ego - upper) / n, 5) if n else None,
            "paired_outcomes": {k: outcomes[k] for k in
                                ("both", "ego_only", "upper_only", "neither")},
            "upper_outside_image": sum(r["upper_center_status"] == "outside_camera_image"
                                       for r in rows),
            "ego_outside_image": sum(r["ego_center_status"] == "outside_camera_image"
                                     for r in rows)}


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path,
                        default=Path("outputs/local/cubberly_native_2d_3d_reprojection_full.csv"))
    parser.add_argument("--source-summary", type=Path,
                        default=Path("outputs/local/cubberly_native_2d_3d_reprojection_full.json"))
    parser.add_argument("--review-csv", type=Path,
                        default=Path("outputs/local/cubberly_reprojection_review_queue.csv"))
    args = parser.parse_args()
    source = json.loads(args.source_summary.read_text())
    if (source.get("sequence") != SEQUENCE or source.get("role") != "development_only"
            or source.get("status") != "exploratory_reference_projection"
            or source.get("frames") != [f"{n:06d}" for n in range(1296)]):
        parser.error("Expected full Cubberly development-only audit summary (1,296 frames)")
    with args.csv.open(newline="", encoding="utf-8-sig") as stream:
        reader = csv.DictReader(stream)
        if not REQUIRED.issubset(reader.fieldnames or []):
            parser.error(f"Missing required CSV columns: {sorted(REQUIRED - set(reader.fieldnames or []))}")
        rows = list(reader)
    if len(rows) != source.get("same_track_frame_camera_pairs"):
        parser.error("CSV row count differs from audit summary")
    seen = set()
    clean = []
    for row in rows:
        key = (row["frame"], row["camera"], row["label_id"])
        if key in seen:
            raise ValueError(f"Duplicate frame-camera-track: {key}")
        seen.add(key)
        if row["frame"] not in source["frames"] or row["camera"] not in {"0", "2", "4", "6", "8"}:
            raise ValueError(f"Unexpected frame or camera: {key}")
        radius = float(row["3d_xy_radius_m"])
        if not math.isfinite(radius) or radius > 3.001 or radius < 0:
            raise ValueError(f"Unexpected near-person radius: {key}")
        box = json.loads(row["2d_box_xywh"])
        if len(box) != 4 or not all(isinstance(v, (int, float)) and
                                    not isinstance(v, bool) and math.isfinite(v) for v in box):
            raise ValueError(f"Invalid 2D box: {key}")
        x, y, w, h = box
        if w <= 0 or h <= 0:
            raise ValueError(f"Nonpositive 2D box: {key}")
        row["image_edge_box"] = x <= 1 or y <= 1 or x + w >= 751 or y + h >= 479
        row["no_eval_bool"] = parse_bool(row["2d_no_eval"], "2d_no_eval")
        row["truncated_bool"] = parse_bool(row["2d_truncated"], "2d_truncated")
        for hypothesis in ("upper", "ego"):
            if row[f"{hypothesis}_center_status"] not in STATUSES:
                raise ValueError(f"Unknown projection status: {key}")
        u = row["upper_center_status"] == "inside_2d_box"
        e = row["ego_center_status"] == "inside_2d_box"
        row["paired_outcome"] = ("both" if u and e else "ego_only" if e else
                                 "upper_only" if u else "neither")
        if row["no_eval_bool"] is False:
            clean.append(row)
    statuses = source.get("projection_statuses_2d_no_eval_false", {})
    if len(clean) != source.get("2d_no_eval_false_pairs") or any(
            Counter(r[f"{hypothesis}_center_status"] for r in clean) != statuses.get(hypothesis)
            for hypothesis in ("upper", "ego")):
        parser.error("CSV status counts differ from audit summary")
    cameras = {str(i): describe([r for r in clean if r["camera"] == str(i)])
               for i in (0, 2, 4, 6, 8)}
    by_frame_track = defaultdict(list)
    by_track = defaultdict(list)
    for row in clean:
        by_frame_track[(row["frame"], row["label_id"])].append(row)
        by_track[row["label_id"]].append(row)
    # Each frame-track counts once here, regardless of how many native views
    # carry its 2D annotation. A view with its projected center outside the
    # camera image is excluded from that frame-track's 'any camera' success.
    unique_frame_track = {
        "count": len(by_frame_track),
        "upper_inside_any_native_view": sum(
            any(r["upper_center_status"] == "inside_2d_box" for r in group)
            for group in by_frame_track.values()),
        "ego_inside_any_native_view": sum(
            any(r["ego_center_status"] == "inside_2d_box" for r in group)
            for group in by_frame_track.values()),
    }
    per_track = {name: {"pairs": len(group), "ego_minus_upper_fraction":
                        (sum(r["ego_center_status"] == "inside_2d_box" for r in group) -
                         sum(r["upper_center_status"] == "inside_2d_box" for r in group)) /
                        len(group)} for name, group in by_track.items()}
    track_deltas = [v["ego_minus_upper_fraction"] for v in per_track.values()]
    near_counts = source.get("near_3d_id_counts_by_frame", {})
    matched = source.get("near_3d_ids_found_in_any_native_2d_view", {})
    if set(near_counts) != set(source["frames"]) or set(matched) != set(source["frames"]):
        parser.error("Source summary lacks complete frame-wise 3D/2D ID coverage")
    near_total = sum(near_counts.values())
    matched_total = 0
    for frame in source["frames"]:
        ids = matched[frame]
        if len(ids) != len(set(ids)) or len(ids) > near_counts[frame]:
            parser.error(f"Inconsistent 3D/2D track coverage at {frame}")
        matched_total += len(ids)
    # Inspect every ego miss and every disagreement; prioritize unclipped,
    # evaluable ego misses. Keep both error directions to avoid cherry-picking.
    review = [r for r in rows if r["paired_outcome"] != "both"]
    for row in review:
        row["review_priority"] = ("1_evaluable_ego_miss_unclipped" if
            row["no_eval_bool"] is False and not row["image_edge_box"] and
            row["ego_center_status"] != "inside_2d_box" else
            "2_evaluable_ego_miss_edge" if row["no_eval_bool"] is False and
            row["ego_center_status"] != "inside_2d_box" else
            "3_upper_miss_ego_inside" if row["no_eval_bool"] is False else
            "4_no_eval_or_unknown")
    review.sort(key=lambda r: (r["review_priority"], r["frame"],
                               int(r["camera"]), r["label_id"]))
    args.review_csv.parent.mkdir(parents=True, exist_ok=True)
    with args.review_csv.open("x", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=REVIEW_FIELDS, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(review)
    report = {
        "status": "development_annotation_consistency_only", "sequence": SEQUENCE,
        "csv_sha256": sha256(args.csv), "source_summary_sha256": sha256(args.source_summary),
        "source_label_3d_sha256": source.get("label_3d_sha256"),
        "source_2d_combined_sha256": source.get("five_2d_members_combined_sha256"),
        "source_calibration_sha256": source.get("calibration_sha256"),
        "all_pairs": describe(rows), "2d_evaluable_pairs": describe(clean),
        "evaluable_unclipped_pairs": describe([r for r in clean if not r["image_edge_box"]]),
        "evaluable_clipped_pairs": describe([r for r in clean if r["image_edge_box"]]),
        "evaluable_occlusion_strata": {key: describe([r for r in clean if
                                    r["2d_occlusion"] == key])
                                      for key in sorted({r["2d_occlusion"] for r in clean})},
        "evaluable_truncation_flag": {
            name: describe([r for r in clean if r["truncated_bool"] is flag])
            for name, flag in (("false", False), ("true", True), ("unknown", None))},
        "per_camera_evaluable": cameras,
        "3d_near_evaluable_frame_tracks": near_total,
        "3d_near_frame_tracks_with_same_id_2d_in_any_view": matched_total,
        "3d_near_frame_tracks_without_same_id_2d": near_total - matched_total,
        "unique_evaluable_frame_tracks": unique_frame_track,
        "track_count": len(per_track),
        "tracks_favor_ego_upper_equal": {
            "ego": sum(d > 0 for d in track_deltas),
            "upper": sum(d < 0 for d in track_deltas),
            "equal": sum(d == 0 for d in track_deltas)},
        "median_per_track_ego_minus_upper_fraction": round(statistics.median(track_deltas), 5)
            if track_deltas else None,
        "top_ego_disagreement_tracks": [
            {"label_id": name, "pairs": v["pairs"], "ego_minus_upper_fraction":
             round(v["ego_minus_upper_fraction"], 5)} for name, v in sorted(
                per_track.items(), key=lambda item: (item[1]["ego_minus_upper_fraction"],
                                                     -item[1]["pairs"]))[:12]],
        "review_queue_csv": str(args.review_csv), "review_queue_rows": len(review),
        "review_priority_counts": dict(Counter(r["review_priority"] for r in review)),
        "interpretation": "Paired 2D/3D annotation agreement on one development sequence; "
            "frames, views and repeated track observations are dependent. Native 2D ID "
            "coverage is annotation coverage, not verified physical visibility. An annotated "
            "2D box near an image edge may exclude the 3D geometric center. Check the "
            "registered images and camera calibration on discrepant cases. These are "
            "not independent calibration, person-range, tracking or alert metrics. "
            "Reference annotations may not enter runtime inference."
    }
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
